In [328]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [329]:
# Load data from CSV files
prediction_data = pd.read_csv("Prediction.csv")
prediction_data

station                   model                 runtime  ftime  n_x  tmp  \
KITH     GFS  2016-01-01 00:00:00+00  2016-01-01 06:00:00+00    NaN   29   26   
KITH     GFS  2016-01-01 00:00:00+00  2016-01-01 09:00:00+00    NaN   28   25   
KITH     GFS  2016-01-01 00:00:00+00  2016-01-01 12:00:00+00    NaN   28   24   
KITH     GFS  2016-01-01 00:00:00+00  2016-01-01 15:00:00+00    NaN   31   24   
KITH     GFS  2016-01-01 00:00:00+00  2016-01-01 18:00:00+00    NaN   32   22   
...      ...                     ...                     ...    ...  ...  ...   
KITH     GFS  2019-12-31 00:00:00+00  2020-01-02 06:00:00+00    NaN   24   18   
KITH     GFS  2019-12-31 00:00:00+00  2020-01-02 09:00:00+00    NaN   24   18   
KITH     GFS  2019-12-31 00:00:00+00  2020-01-02 12:00:00+00   20.0   25   19   
KITH     GFS  2019-12-31 00:00:00+00  2020-01-02 18:00:00+00    NaN   43   26   
KITH     GFS  2019-12-31 00:00:00+00  2020-01-03 00:00:00+00   45.0   38   27   

     dpt  cld  wdr   wsp  ...  lcb  i06  slv s06 pra  ppl  psn  pzr t03  gst  
KITH  OV  300    6   NaN  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  OV  290    7   NaN  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  OV  260    6  29.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  OV  260   10   NaN  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  OV  270   12  31.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
...   ..  ...  ...   ...  ...  ...  ...  ...  ..  ..  ...  ...  ...  ..  ...  
KITH  CL  250    7   1.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  CL  170    5   NaN  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  FW  170    6   1.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  FW  210   10   0.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  
KITH  OV  170    7   0.0  ...  NaN  NaN  NaN NaN NaN  NaN  NaN  NaN NaN  NaN  

[124152 rows x 35 columns]

In [330]:
prediction_data['runtime'] = pd.to_datetime(prediction_data['runtime'], format='%Y-%m-%d %H:%M:%S').dt.tz_convert(None)

In [331]:
prediction_data['runtime']

KITH   2016-01-01 06:00:00
KITH   2016-01-01 09:00:00
KITH   2016-01-01 12:00:00
KITH   2016-01-01 15:00:00
KITH   2016-01-01 18:00:00
               ...        
KITH   2020-01-02 06:00:00
KITH   2020-01-02 09:00:00
KITH   2020-01-02 12:00:00
KITH   2020-01-02 18:00:00
KITH   2020-01-03 00:00:00
Name: runtime, Length: 124152, dtype: datetime64[ns]

In [332]:
df_prediction = prediction_data.set_index('runtime')

In [333]:
df_prediction = df_prediction.groupby(df_prediction.index).mean()

In [334]:
df_prediction

ftime        n_x        tmp    cld        wdr   wsp  \
runtime                                                                        
2016-01-01 06:00:00        NaN  29.000000  26.000000  300.0   6.000000   NaN   
2016-01-01 09:00:00        NaN  28.000000  25.000000  290.0   7.000000   NaN   
2016-01-01 12:00:00        NaN  29.000000  24.500000  265.0   6.500000  29.0   
2016-01-01 15:00:00        NaN  31.500000  24.000000  260.0  10.000000   NaN   
2016-01-01 18:00:00        NaN  31.666667  23.000000  270.0  11.000000  31.5   
...                        ...        ...        ...    ...        ...   ...   
2020-01-02 06:00:00        NaN  24.500000  17.250000  265.0   7.250000   1.5   
2020-01-02 09:00:00        NaN  24.000000  18.000000  170.0   5.000000   NaN   
2020-01-02 12:00:00  20.333333  25.333333  18.666667  170.0   5.666667   2.0   
2020-01-02 18:00:00        NaN  42.000000  25.000000  215.0   9.500000   0.5   
2020-01-03 00:00:00  45.000000  38.000000  27.000000  170.0   7.000000   0.0   

                          p06  p12  q06  t12  ...  lcb  i06  slv  s06  pra  \
runtime                                       ...                            
2016-01-01 06:00:00       NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2016-01-01 09:00:00       NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2016-01-01 12:00:00       NaN  0.0  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2016-01-01 15:00:00       NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2016-01-01 18:00:00       NaN  0.0  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
...                       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2020-01-02 06:00:00       NaN  0.0  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2020-01-02 09:00:00       NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2020-01-02 12:00:00  3.666667  0.0  0.0  0.0  ...  NaN  NaN  NaN  NaN  NaN   
2020-01-02 18:00:00       NaN  0.0  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
2020-01-03 00:00:00  0.000000  0.0  0.0  NaN  ...  NaN  NaN  NaN  NaN  NaN   

                     ppl  psn  pzr  t03  gst  
runtime                                       
2016-01-01 06:00:00  NaN  NaN  NaN  NaN  NaN  
2016-01-01 09:00:00  NaN  NaN  NaN  NaN  NaN  
2016-01-01 12:00:00  NaN  NaN  NaN  NaN  NaN  
2016-01-01 15:00:00  NaN  NaN  NaN  NaN  NaN  
2016-01-01 18:00:00  NaN  NaN  NaN  NaN  NaN  
...                  ...  ...  ...  ...  ...  
2020-01-02 06:00:00  NaN  NaN  NaN  NaN  NaN  
2020-01-02 09:00:00  NaN  NaN  NaN  NaN  NaN  
2020-01-02 12:00:00  NaN  NaN  NaN  NaN  NaN  
2020-01-02 18:00:00  NaN  NaN  NaN  NaN  NaN  
2020-01-03 00:00:00  NaN  NaN  NaN  NaN  NaN  

[11701 rows x 27 columns]

In [335]:
Every_three_hour = df_prediction.index.set_names("Prediction 3 hours intervals")

In [336]:
Every_three_hour = pd.to_datetime(Every_three_hour, format='%Y-%m-%d %H:%M:%S')

In [337]:
Every_three_hour

DatetimeIndex(['2016-01-01 06:00:00', '2016-01-01 09:00:00',
               '2016-01-01 12:00:00', '2016-01-01 15:00:00',
               '2016-01-01 18:00:00', '2016-01-01 21:00:00',
               '2016-01-02 00:00:00', '2016-01-02 03:00:00',
               '2016-01-02 06:00:00', '2016-01-02 09:00:00',
               ...
               '2020-01-01 15:00:00', '2020-01-01 18:00:00',
               '2020-01-01 21:00:00', '2020-01-02 00:00:00',
               '2020-01-02 03:00:00', '2020-01-02 06:00:00',
               '2020-01-02 09:00:00', '2020-01-02 12:00:00',
               '2020-01-02 18:00:00', '2020-01-03 00:00:00'],
              dtype='datetime64[ns]', name='Prediction 3 hours intervals', length=11701, freq=None)

In [338]:
Temperature_prediction = df_prediction.n_x.values

In [339]:
Temperature_prediction

array([29.        , 28.        , 29.        , ..., 25.33333333,
       42.        , 38.        ])

In [340]:
Tmp_DataFrame = {"Prediction time": Every_three_hour, "Temperature predictions": Temperature_prediction}
Tmp_DataFrame = pd.DataFrame(Tmp_DataFrame)
Tmp_DataFrame = Tmp_DataFrame.set_index("Prediction time")
Tmp_DataFrame.index = pd.to_datetime(Tmp_DataFrame.index, format='%Y-%m-%d %H:%M')

In [341]:
Tmp_DataFrame

Temperature predictions
Prediction time                             
2016-01-01 06:00:00                29.000000
2016-01-01 09:00:00                28.000000
2016-01-01 12:00:00                29.000000
2016-01-01 15:00:00                31.500000
2016-01-01 18:00:00                31.666667
...                                      ...
2020-01-02 06:00:00                24.500000
2020-01-02 09:00:00                24.000000
2020-01-02 12:00:00                25.333333
2020-01-02 18:00:00                42.000000
2020-01-03 00:00:00                38.000000

[11701 rows x 1 columns]

In [342]:
df_temp_predict = Tmp_DataFrame.reindex(pd.date_range(start='2016-01-01', end='2020-01-03', freq='H'), index='Prediction time', fill_value=None)
interpolate_temp = df_temp_predict['Temperature predictions'].interpolate(method="linear")

In [343]:
df_temp_predict

Temperature predictions
2016-01-01 00:00:00                      NaN
2016-01-01 01:00:00                      NaN
2016-01-01 02:00:00                      NaN
2016-01-01 03:00:00                      NaN
2016-01-01 04:00:00                      NaN
...                                      ...
2020-01-02 20:00:00                      NaN
2020-01-02 21:00:00                      NaN
2020-01-02 22:00:00                      NaN
2020-01-02 23:00:00                      NaN
2020-01-03 00:00:00                     38.0

[35113 rows x 1 columns]

In [344]:
interpolate_temp

2016-01-01 00:00:00          NaN
2016-01-01 01:00:00          NaN
2016-01-01 02:00:00          NaN
2016-01-01 03:00:00          NaN
2016-01-01 04:00:00          NaN
                         ...    
2020-01-02 20:00:00    40.666667
2020-01-02 21:00:00    40.000000
2020-01-02 22:00:00    39.333333
2020-01-02 23:00:00    38.666667
2020-01-03 00:00:00    38.000000
Freq: H, Name: Temperature predictions, Length: 35113, dtype: float64

In [345]:
est_temp = interpolate_temp[5:]

In [346]:
est_temp[0] = 28.5

In [347]:
convert_far_cel = lambda x: 5/9*(x-32)

In [348]:
est_temp_in_range = convert_far_cel(est_temp[:-44])
est_temp_in_range

2016-01-01 05:00:00   -1.944444
2016-01-01 06:00:00   -1.666667
2016-01-01 07:00:00   -1.851852
2016-01-01 08:00:00   -2.037037
2016-01-01 09:00:00   -2.222222
                         ...   
2020-01-01 00:00:00    0.308642
2020-01-01 01:00:00   -0.195473
2020-01-01 02:00:00   -0.699588
2020-01-01 03:00:00   -1.203704
2020-01-01 04:00:00   -1.520062
Freq: H, Name: Temperature predictions, Length: 35064, dtype: float64

In [349]:
whole_four_years = pd.date_range(start='2016-01-01', end='2020-01-01', freq='H')
predict_whole_four_year_df = {"time": whole_four_years[:-1], "predicted temp": est_temp_in_range.values}
PredictDataFrame = pd.DataFrame(predict_whole_four_year_df)

In [352]:
PredictDataFrame

time  predicted temp
0     2016-01-01 00:00:00       -1.944444
1     2016-01-01 01:00:00       -1.666667
2     2016-01-01 02:00:00       -1.851852
3     2016-01-01 03:00:00       -2.037037
4     2016-01-01 04:00:00       -2.222222
...                   ...             ...
35059 2019-12-31 19:00:00        0.308642
35060 2019-12-31 20:00:00       -0.195473
35061 2019-12-31 21:00:00       -0.699588
35062 2019-12-31 22:00:00       -1.203704
35063 2019-12-31 23:00:00       -1.520062

[35064 rows x 2 columns]

In [353]:
true_data = pd.read_csv("IthacaWeather.csv")
true_temp = true_data['temp']
true_temp

0        0.1
1        0.3
2        0.3
3        0.3
4        0.3
        ... 
35059    0.6
35060    0.0
35061    0.0
35062   -0.6
35063   -0.6
Name: temp, Length: 35064, dtype: float64

In [354]:
true_predict_std = np.std(np.array(PredictDataFrame['predicted temp']) - np.array(true_temp))

In [355]:
true_predict_std

1.888840866954095

In [356]:
est_temp_6 = convert_far_cel(est_temp[6:-38])
est_temp_6

2016-01-01 11:00:00   -1.851852
2016-01-01 12:00:00   -1.666667
2016-01-01 13:00:00   -1.203704
2016-01-01 14:00:00   -0.740741
2016-01-01 15:00:00   -0.277778
                         ...   
2020-01-01 06:00:00   -2.152778
2020-01-01 07:00:00   -2.472222
2020-01-01 08:00:00   -2.791667
2020-01-01 09:00:00   -3.111111
2020-01-01 10:00:00   -3.211640
Freq: H, Name: Temperature predictions, Length: 35064, dtype: float64

In [357]:
est_temp_12 = convert_far_cel(interpolate_temp[5:-32])
predict_temp_12 = est_temp_12[12:]

In [359]:
predict_temp_12

2016-01-01 17:00:00   -0.216049
2016-01-01 18:00:00   -0.185185
2016-01-01 19:00:00   -0.617284
2016-01-01 20:00:00   -1.049383
2016-01-01 21:00:00   -1.481481
                         ...   
2020-01-01 12:00:00   -3.412698
2020-01-01 13:00:00   -2.784392
2020-01-01 14:00:00   -2.156085
2020-01-01 15:00:00   -1.527778
2020-01-01 16:00:00   -1.018519
Freq: H, Name: Temperature predictions, Length: 35064, dtype: float64

In [360]:
est_temp_24 = convert_far_cel(interpolate_temp[5:-20])
predict_temp_24 = est_temp_24[24:]

In [361]:
noise_12 = np.random.normal(0, true_predict_std/6, [35064,1])

In [362]:
noise_12

array([[ 0.4330395 ],
       [-0.19266718],
       [ 0.43069448],
       ...,
       [-0.01760942],
       [-0.07434604],
       [-0.16602265]])

In [363]:
noise_24 = np.random.normal(0, true_predict_std/3, [35064,1])

In [364]:
noise_predict_12 = np.add(predict_temp_12.values.reshape(35064,1), noise_12)

In [365]:
noise_predict_24 = np.add(predict_temp_24.values.reshape(35064,1), noise_24)

In [366]:
noise_predict_12

array([[ 0.21699012],
       [-0.37785237],
       [-0.18658948],
       ...,
       [-2.17369408],
       [-1.60212381],
       [-1.18454117]])

In [367]:
noise_predict_24

array([[-3.77120515],
       [-3.72296708],
       [-2.95250166],
       ...,
       [-1.8761904 ],
       [-2.17284514],
       [-1.79850807]])

In [407]:
import math
calculate_rh = lambda dpt, tmp: 100*(math.exp((17.625*dpt)/(243.04+dpt))/math.exp((17.625*tmp)/(243.04+tmp)))

In [380]:
Dewpoint_prediction = df_prediction.tmp.values

In [381]:
Dpt_DataFrame = {"Prediction time": Every_three_hour, "Dew point predictions": Dewpoint_prediction}
Dpt_DataFrame = pd.DataFrame(Dpt_DataFrame)
Dpt_DataFrame = Dpt_DataFrame.set_index("Prediction time")
Dpt_DataFrame.index = pd.to_datetime(Dpt_DataFrame.index, format='%Y-%m-%d %H:%M')

In [382]:
df_dpt_predict = Dpt_DataFrame.reindex(pd.date_range(start='2016-01-01', end='2020-01-03', freq='H'), index='Prediction time', fill_value=None)
interpolate_dpt = df_dpt_predict['Dew point predictions'].interpolate(method="linear")

In [411]:
est_dpt = interpolate_dpt[5:]
est_dpt[0] = 27
est_dpt_in_range = convert_far_cel(est_dpt[:-44])

In [415]:
def calculate_rh_lst(dpts, tmps):
    res = []
    for dpt, tmp in zip(dpts, tmps):
        res.append(calculate_rh(dpt, tmp))
    return np.array(res)

In [417]:
whole_four_years = pd.date_range(start='2016-01-01', end='2020-01-01', freq='H')
predict_rh_whole_four_year_df = calculate_rh_lst(est_dpt_in_range, est_temp_in_range)
predict_rh_whole_four_year_df = {"time": whole_four_years[:-1], "predicted RH": predict_rh_whole_four_year_df}
PredictDptDataFrame = pd.DataFrame(predict_rh_whole_four_year_df)

In [418]:
PredictDptDataFrame

time  predicted RH
0     2016-01-01 00:00:00     94.023621
1     2016-01-01 01:00:00     88.391729
2     2016-01-01 02:00:00     88.374918
3     2016-01-01 03:00:00     88.358070
4     2016-01-01 04:00:00     88.341187
...                   ...           ...
35059 2019-12-31 19:00:00     78.672481
35060 2019-12-31 20:00:00     78.112095
35061 2019-12-31 21:00:00     77.550857
35062 2019-12-31 22:00:00     76.988795
35063 2019-12-31 23:00:00     76.756262

[35064 rows x 2 columns]

In [420]:
true_rh = true_data['humidity']
true_predict_rh_std = np.std(np.array(PredictDptDataFrame['predicted RH']) - np.array(true_rh))

10.042623625798164

In [437]:
est_rh_6 = calculate_rh_lst(convert_far_cel(interpolate_dpt[5:-38]), convert_far_cel(interpolate_temp[5:-38]))
predict_rh_6 = est_rh_6[6:]

In [438]:
est_rh_12 = calculate_rh_lst(convert_far_cel(interpolate_dpt[5:-32]), convert_far_cel(interpolate_temp[5:-32]))
predict_rh_12 = est_rh_12[12:]

In [439]:
est_rh_24 = calculate_rh_lst(convert_far_cel(interpolate_dpt[5:-20]), convert_far_cel(interpolate_temp[5:-20]))
predict_rh_24 = est_rh_24[24:]

In [444]:
noise_rh_12 = np.random.normal(0, true_predict_rh_std/5, [35064,1])
noise_rh_24 = np.random.normal(0, true_predict_rh_std/3, [35064,1])

In [449]:
noise_predict_rh_12 = np.add(predict_rh_12.reshape(35064,1), noise_rh_12)
noise_predict_rh_24 = np.add(predict_rh_24.reshape(35064,1), noise_rh_24)

In [470]:
PredictionDataFrame = {"6h Prediction Outdoor Drybulb Temperature [C]": est_temp_6.values.tolist(), "12h Prediction Outdoor Drybulb Temperature [C]": noise_predict_12.flatten().tolist(), "24h Prediction Outdoor Drybulb Temperature [C]": noise_predict_24.flatten().tolist(), "6h Prediction Outdoor Relative Humidity [%]": predict_rh_6.tolist(), "12h Prediction Outdoor Relative Humidity [%]": noise_predict_rh_12.flatten().tolist(), "24h Prediction Outdoor Relative Humidity [%]": noise_predict_rh_24.flatten().tolist()}
PredictionDataFrame = pd.DataFrame(PredictionDataFrame)
PredictionDataFrame.to_csv("processed/Prediction.csv", index=False)