In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [81]:
# Load data from CSV files
weather_data = pd.read_csv("IthacaWeather.csv")
weather_data

name             datetime  temp  feelslike  dew  humidity  precip  \
0      Ithaca  2016-01-01T00:00:00   0.1       -3.6 -2.0     85.93    0.00   
1      Ithaca  2016-01-01T01:00:00   0.3       -4.1 -2.6     80.78    0.09   
2      Ithaca  2016-01-01T02:00:00   0.3       -4.3 -3.0     78.65    0.00   
3      Ithaca  2016-01-01T03:00:00   0.3       -5.0 -3.4     76.60    0.00   
4      Ithaca  2016-01-01T04:00:00   0.3       -4.6 -3.3     76.80    0.00   
...       ...                  ...   ...        ...  ...       ...     ...   
35059  Ithaca  2019-12-31T19:00:00   0.6       -5.2 -6.1     60.75    0.00   
35060  Ithaca  2019-12-31T20:00:00   0.0       -5.8 -5.6     65.86    0.00   
35061  Ithaca  2019-12-31T21:00:00   0.0       -4.7 -5.7     65.64    0.00   
35062  Ithaca  2019-12-31T22:00:00  -0.6       -6.1 -5.0     72.15    0.00   
35063  Ithaca  2019-12-31T23:00:00  -0.6       -5.8 -5.7     68.78    0.00   

       precipprob preciptype  snow  ...  sealevelpressure  cloudcover  \
0               0        NaN  0.00  ...            1018.7       100.0   
1             100  rain,snow  0.00  ...            1018.0       100.0   
2               0        NaN  0.00  ...            1018.0       100.0   
3               0        NaN  0.00  ...            1017.8       100.0   
4               0        NaN  0.00  ...            1017.5       100.0   
...           ...        ...   ...  ...               ...         ...   
35059           0        NaN  0.04  ...            1003.1        24.4   
35060           0        NaN  0.04  ...            1002.9        13.9   
35061           0        NaN  0.04  ...            1003.0        47.0   
35062           0        NaN  0.04  ...            1003.2        47.4   
35063           0        NaN  0.04  ...            1003.1        47.4   

       visibility  solarradiation  solarenergy  uvindex  severerisk  \
0            13.0             0.0          NaN        0         NaN   
1            14.5             0.0          NaN        0         NaN   
2            15.4             0.0          NaN        0         NaN   
3            15.4             0.0          NaN        0         NaN   
4            16.0             0.0          NaN        0         NaN   
...           ...             ...          ...      ...         ...   
35059        16.0           135.0          0.5        0         NaN   
35060        16.0           135.0          0.5        0         NaN   
35061        16.0           135.0          0.5        0         NaN   
35062        16.0           135.0          0.5        0         NaN   
35063        16.0           135.0          0.5        0         NaN   

                 conditions    icon  \
0                  Overcast  cloudy   
1      Snow, Rain, Overcast    rain   
2                  Overcast  cloudy   
3                  Overcast  cloudy   
4                  Overcast  cloudy   
...                     ...     ...   
35059      Partially cloudy    snow   
35060                 Clear    snow   
35061      Partially cloudy    snow   
35062      Partially cloudy    snow   
35063      Partially cloudy    snow   

                                                stations  
0      72519454778,KELM,72515614748,72515004725,KPEO,...  
1      72519454778,KELM,72515614748,72515004725,KPEO,...  
2      72519454778,KELM,72515614748,72515004725,KPEO,...  
3      72519454778,KELM,72515614748,72515004725,KPEO,...  
4      72519454778,KELM,72515614748,72515004725,KPEO,...  
...                                                  ...  
35059  KITH,72515594761,F4679,KELM,72515614748,725150...  
35060  KITH,72515594761,F4679,KELM,72515614748,725150...  
35061  KITH,72515594761,F4679,KELM,72515614748,725150...  
35062  KITH,72515594761,F4679,KELM,72515614748,725150...  
35063  KITH,72515594761,F4679,KELM,72515614748,725150...  

[35064 rows x 24 columns]

In [131]:
weather_data["datetime"] = pd.to_datetime(weather_data["datetime"], format='%Y-%m-%d %H:%M:%S')

In [132]:
weather_data["datetime"]

0       2016-01-01 00:00:00
1       2016-01-01 01:00:00
2       2016-01-01 02:00:00
3       2016-01-01 03:00:00
4       2016-01-01 04:00:00
                ...        
35059   2019-12-31 19:00:00
35060   2019-12-31 20:00:00
35061   2019-12-31 21:00:00
35062   2019-12-31 22:00:00
35063   2019-12-31 23:00:00
Name: datetime, Length: 35064, dtype: datetime64[ns]

In [133]:
temperature = weather_data["temp"]
humidity = weather_data["humidity"]
solar = weather_data["solarradiation"]

In [134]:
useful_dict = {"Outdoor Drybulb Temperature [C]": temperature, "Outdoor Relative Humidity [%]": humidity}

In [135]:
climate_zone5 = pd.read_csv("../Climate_Zone_5/weather_data.csv")

In [136]:
diffuse_solar = climate_zone5["Diffuse Solar Radiation [W/m2]"]
direct_solar = climate_zone5["Direct Solar Radiation [W/m2]"]

In [137]:
diffuse_direct_cor = diffuse_solar/(direct_solar+diffuse_solar)
direct_diffuse_cor = direct_solar/(direct_solar+diffuse_solar)

In [138]:
diffuse_direct_cor_df = diffuse_direct_cor.to_frame()
diffuse_direct_cor_df.replace([np.inf, -np.inf], 1., inplace=True)
direct_diffuse_cor_df = direct_diffuse_cor.to_frame()
direct_diffuse_cor_df.replace([np.inf, -np.inf], 1., inplace=True)

In [139]:
diffuse_direct_cor_df = diffuse_direct_cor_df.fillna(0.)
direct_diffuse_cor_df = direct_diffuse_cor_df.fillna(0.)

In [140]:
diffuse_direct_cor_df

0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
35035  0.0
35036  0.0
35037  0.0
35038  0.0
35039  0.0

[35040 rows x 1 columns]

In [141]:
diffuse_last_24 = diffuse_direct_cor[-24:]
direct_last_24 = direct_diffuse_cor[-24:]

In [142]:
diffuse_direct_cor_df_long = np.append(diffuse_direct_cor_df, diffuse_last_24)
direct_diffuse_cor_df_long = np.append(direct_diffuse_cor_df, direct_last_24)

In [143]:
whole_four_years = pd.date_range(start='2016-01-01', end='2020-01-01', freq='H')

In [144]:
diffuse_direct_dict = {"Time": whole_four_years[:-1], "Solar": diffuse_direct_cor_df_long}
direct_diffuse_dict = {"Time": whole_four_years[:-1], "Solar": direct_diffuse_cor_df_long}

In [145]:
diffuse_direct_df = pd.DataFrame(diffuse_direct_dict)
direct_diffuse_df = pd.DataFrame(direct_diffuse_dict)

In [146]:
diffuse_solar_ithaca = solar.values * diffuse_direct_cor_df_long
direct_solar_ithaca = solar.values * direct_diffuse_cor_df_long

In [147]:
direct_solar_ithaca

array([ 0.,  0.,  0., ..., nan, nan, nan])

In [148]:
solar_ithaca_dict = {"Diffuse Solar Radiation [W/m2]": diffuse_solar_ithaca, "Direct Solar Radiation [W/m2]": direct_solar_ithaca}

In [149]:
solar_ithaca_df = pd.DataFrame(solar_ithaca_dict)

In [150]:
solar_ithaca_df = solar_ithaca_df.fillna(0.)

In [151]:
solar_ithaca_df

Diffuse Solar Radiation [W/m2]  Direct Solar Radiation [W/m2]
0                                 0.0                            0.0
1                                 0.0                            0.0
2                                 0.0                            0.0
3                                 0.0                            0.0
4                                 0.0                            0.0
...                               ...                            ...
35059                             0.0                            0.0
35060                             0.0                            0.0
35061                             0.0                            0.0
35062                             0.0                            0.0
35063                             0.0                            0.0

[35064 rows x 2 columns]

In [167]:
solar_ithaca_df.to_csv("processed/SolarRadiation.csv", index=False)

In [168]:
climate_5_diffuse_6h_noise = climate_zone5["6h Prediction Diffuse Solar Radiation [W/m2]"]-climate_zone5["Diffuse Solar Radiation [W/m2]"]
climate_5_diffuse_12h_noise = climate_zone5["12h Prediction Diffuse Solar Radiation [W/m2]"]-climate_zone5["Diffuse Solar Radiation [W/m2]"]
climate_5_diffuse_24h_noise = climate_zone5["24h Prediction Diffuse Solar Radiation [W/m2]"]-climate_zone5["Diffuse Solar Radiation [W/m2]"]

In [169]:
climate_5_direct_6h_noise = climate_zone5["6h Prediction Direct Solar Radiation [W/m2]"] - climate_zone5[
    "Direct Solar Radiation [W/m2]"]
climate_5_direct_12h_noise = climate_zone5["12h Prediction Direct Solar Radiation [W/m2]"] - climate_zone5[
    "Direct Solar Radiation [W/m2]"]
climate_5_direct_24h_noise = climate_zone5["24h Prediction Direct Solar Radiation [W/m2]"] - climate_zone5[
    "Direct Solar Radiation [W/m2]"]

In [170]:
climate_5_diffuse_6h_noise

0         -0.00
1         16.77
2         40.08
3         65.63
4        107.26
          ...  
35035     -0.00
35036     -0.00
35037      0.00
35038      0.00
35039     -0.00
Length: 35040, dtype: float64

In [198]:
climate_5_diffuse_6h_noise = np.append(climate_5_diffuse_6h_noise, climate_5_diffuse_6h_noise[-24:])
climate_5_diffuse_12h_noise = np.append(climate_5_diffuse_12h_noise, climate_5_diffuse_12h_noise[-24:])
climate_5_diffuse_24h_noise = np.append(climate_5_diffuse_24h_noise, climate_5_diffuse_24h_noise[-24:])

In [199]:
climate_5_direct_6h_noise = np.append(climate_5_direct_6h_noise, climate_5_direct_6h_noise[-24:])
climate_5_direct_12h_noise = np.append(climate_5_direct_12h_noise, climate_5_direct_12h_noise[-24:])
climate_5_direct_24h_noise = np.append(climate_5_direct_24h_noise, climate_5_direct_24h_noise[-24:])

In [218]:
long_diffuse_6h_predict = np.append(climate_zone5["6h Prediction Diffuse Solar Radiation [W/m2]"],climate_zone5["6h Prediction Diffuse Solar Radiation [W/m2]"][-24:])
long_diffuse_12h_predict = np.append(climate_zone5["12h Prediction Diffuse Solar Radiation [W/m2]"],climate_zone5["12h Prediction Diffuse Solar Radiation [W/m2]"][-24:])
long_diffuse_24h_predict = np.append(climate_zone5["24h Prediction Diffuse Solar Radiation [W/m2]"],climate_zone5["24h Prediction Diffuse Solar Radiation [W/m2]"][-24:])

In [219]:
long_direct_6h_predict = np.append(climate_zone5["6h Prediction Direct Solar Radiation [W/m2]"],climate_zone5["6h Prediction Direct Solar Radiation [W/m2]"][-24:])
long_direct_12h_predict = np.append(climate_zone5["12h Prediction Direct Solar Radiation [W/m2]"],climate_zone5["12h Prediction Direct Solar Radiation [W/m2]"][-24:])
long_direct_24h_predict = np.append(climate_zone5["24h Prediction Direct Solar Radiation [W/m2]"],climate_zone5["24h Prediction Direct Solar Radiation [W/m2]"][-24:])

In [236]:
shuffle_climate_5_diffuse_6h = np.append(long_diffuse_6h_predict[-6:], long_diffuse_6h_predict[:-6])
shuffle_climate_5_diffuse_12h = np.append(long_diffuse_12h_predict[-12:], long_diffuse_12h_predict[:-12])
shuffle_climate_5_diffuse_24h = np.append(long_diffuse_24h_predict[-24:], long_diffuse_24h_predict[:-24])

In [237]:
shuffle_climate_5_direct_6h = np.append(long_direct_6h_predict[-6:], long_direct_6h_predict[:-6])
shuffle_climate_5_direct_12h = np.append(long_direct_12h_predict[-12:], long_direct_12h_predict[:-12])
shuffle_climate_5_direct_24h = np.append(long_direct_24h_predict[-24:], long_direct_24h_predict[:-24])

In [249]:
long_diffuse_solar = np.append(climate_zone5["Diffuse Solar Radiation [W/m2]"],climate_zone5["Diffuse Solar Radiation [W/m2]"][-24:])
long_direct_solar = np.append(climate_zone5["Direct Solar Radiation [W/m2]"],climate_zone5["Direct Solar Radiation [W/m2]"][-24:])

In [250]:
shuffle_climate_5_diffuse_6h_noise = shuffle_climate_5_diffuse_6h - long_diffuse_solar
shuffle_climate_5_diffuse_12h_noise = shuffle_climate_5_diffuse_12h - long_diffuse_solar
shuffle_climate_5_diffuse_24h_noise = shuffle_climate_5_diffuse_24h - long_diffuse_solar

In [251]:
shuffle_climate_5_direct_6h_noise = shuffle_climate_5_direct_6h - long_direct_solar
shuffle_climate_5_direct_12h_noise = shuffle_climate_5_direct_12h - long_direct_solar
shuffle_climate_5_direct_24h_noise = shuffle_climate_5_direct_24h - long_direct_solar

In [252]:
shuffle_climate_5_diffuse_6h_noise

array([ 0., -0., -0., ..., -0.,  0., -0.])

In [253]:
climate_5_diffuse_6h_noise

array([-0.  , 16.77, 40.08, ...,  0.  ,  0.  , -0.  ])

In [254]:
ithaca_diffuse_predict_6h = shuffle_climate_5_diffuse_6h_noise + solar_ithaca_df["Diffuse Solar Radiation [W/m2]"]
ithaca_diffuse_predict_12h = shuffle_climate_5_diffuse_12h_noise  + solar_ithaca_df["Diffuse Solar Radiation [W/m2]"]
ithaca_diffuse_predict_24h = shuffle_climate_5_diffuse_24h_noise  + solar_ithaca_df["Diffuse Solar Radiation [W/m2]"]

In [255]:
ithaca_direct_predict_6h = shuffle_climate_5_direct_6h_noise + solar_ithaca_df["Direct Solar Radiation [W/m2]"]
ithaca_direct_predict_12h = shuffle_climate_5_direct_12h_noise  + solar_ithaca_df["Direct Solar Radiation [W/m2]"]
ithaca_direct_predict_24h = shuffle_climate_5_direct_24h_noise  + solar_ithaca_df["Direct Solar Radiation [W/m2]"]

In [258]:
np.array(ithaca_diffuse_predict_6h)

array([0., 0., 0., ..., 0., 0., 0.])

In [263]:
Ithaca_Diffuse_Predict_6h = np.append(ithaca_diffuse_predict_6h[6:], ithaca_diffuse_predict_6h[-6:])
Ithaca_Diffuse_Predict_12h = np.append(ithaca_diffuse_predict_12h[12:], ithaca_diffuse_predict_12h[-12:])
Ithaca_Diffuse_Predict_24h = np.append(ithaca_diffuse_predict_24h[24:], ithaca_diffuse_predict_24h[-24:])

In [264]:
Ithaca_Diffuse_Predict_6h

array([ 0.        ,  4.57888889, 92.76665084, ...,  0.        ,
        0.        ,  0.        ])

In [265]:
Ithaca_Direct_Predict_6h = np.append(ithaca_direct_predict_6h[6:], ithaca_direct_predict_6h[-6:])
Ithaca_Direct_Predict_12h = np.append(ithaca_direct_predict_12h[12:], ithaca_direct_predict_12h[-12:])
Ithaca_Direct_Predict_24h = np.append(ithaca_direct_predict_24h[24:], ithaca_direct_predict_24h[-24:])

In [266]:
ithaca_solar_predict_dict = {"6h Prediction Diffuse Solar Radiation [W/m2]": Ithaca_Diffuse_Predict_6h, "12h Prediction Diffuse Solar Radiation [W/m2]": Ithaca_Diffuse_Predict_12h, "24h Prediction Diffuse Solar Radiation [W/m2]": Ithaca_Diffuse_Predict_24h, "6h Prediction Direct Solar Radiation [W/m2]": Ithaca_Direct_Predict_6h, "12h Prediction Direct Solar Radiation [W/m2]": Ithaca_Direct_Predict_12h, "24h Prediction Direct Solar Radiation [W/m2]": Ithaca_Direct_Predict_24h}

In [267]:
Ithaca_Solar_Predict_DF = pd.DataFrame(ithaca_solar_predict_dict)

In [273]:
Ithaca_Solar_Predict_DF.to_csv("./processed/IthacaSolarPrediction.csv", index=False)

In [274]:
Temp_RH_df = pd.DataFrame(useful_dict)

In [275]:
Temp_RH_df.to_csv("./processed/IthacaWeather.csv", index=False)

In [276]:
solar

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
         ...  
35059    135.0
35060    135.0
35061    135.0
35062    135.0
35063    135.0
Name: solarradiation, Length: 35064, dtype: float64

In [278]:
solar_generation_dict = {"Hours since 00:00 Jan 1": np.arange(35064), "Hourly Data: AC inverter power (W)": solar}

In [279]:
Solar_Generation_df = pd.DataFrame(solar_generation_dict)

In [281]:
Solar_Generation_df.to_csv("../Cornell_Simulation/solar_generation_1kW.csv", index=False)